# Generated by Django 3.0.2 on 2020-01-12 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0004_auto_20200109_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Courses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Words')),
            ],
        ),
    ]
