# Generated by Django 3.0.2 on 2020-02-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200204_2337'),
        ('answers', '0003_auto_20200204_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='word',
        ),
        migrations.AddField(
            model_name='answers',
            name='word',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Words'),
            preserve_default=False,
        ),
    ]
