# Generated by Django 3.0.2 on 2020-03-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200301_1914'),
        ('answers', '0004_auto_20200205_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='word',
        ),
        migrations.AlterField(
            model_name='answers',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_course', to='courses.Courses'),
        ),
    ]
