# Generated by Django 3.0.2 on 2020-03-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200301_1914'),
        ('answers', '0005_auto_20200301_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.AddField(
            model_name='answers',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answers',
            name='cours',
            field=models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer_course', to='courses.Courses'),
        ),
    ]
