# Generated by Django 3.0.2 on 2020-03-01 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200301_1914'),
        ('answers', '0007_auto_20200301_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='word',
        ),
        migrations.AddField(
            model_name='answers',
            name='course',
            field=models.ForeignObject(from_fields=('name', 'user', 'word'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_answer', to='courses.Courses', to_fields=('name', 'user', 'word')),
        ),
    ]
