# Generated by Django 3.0.2 on 2020-03-01 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200301_1914'),
        ('answers', '0008_auto_20200301_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='course',
        ),
        migrations.AddField(
            model_name='answers',
            name='cours',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.Courses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answers',
            name='word',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
