# Generated by Django 3.0.2 on 2020-03-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0010_auto_20200301_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='cours',
            new_name='course',
        ),
    ]
