version: '3'
volumes:
  postgres_volume:

services:
  postgres:
    container_name: eng-app
    image: postgres:11
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"