version: '3'
volumes:
  postgres_volume:

services:
  django:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend
    ports:
      - 8008:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: eng-app
    image: postgres:11
    env_file:
      - .env

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"