# Generated by Django 2.0.9 on 2019-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appeng', '0002_auto_20190509_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_answer',
            name='user_score',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
