# Generated by Django 3.0.2 on 2020-02-04 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_cur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='word',
            field=models.ManyToManyField(blank=True, to='courses.Words'),
        ),
    ]
