# Generated by Django 3.0.6 on 2020-05-09 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(
                blank=True,
                related_name='user_cur',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='courses',
            name='word',
            field=models.ManyToManyField(blank=True, to='courses.Words'),
        ),
    ]
