# Generated by Django 3.0.2 on 2020-03-01 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20200204_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(related_name='user_cur', to=settings.AUTH_USER_MODEL),
        ),
    ]
