# Generated by Django 3.0.2 on 2020-03-22 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20200301_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(null=True, related_name='user_cur', to=settings.AUTH_USER_MODEL),
        ),
    ]
