# Generated by Django 3.0.2 on 2020-01-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200109_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='word',
        ),
        migrations.AddField(
            model_name='courses',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Words'),
        ),
    ]
