# Generated by Django 3.0.2 on 2020-01-12 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0006_auto_20200112_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='users',
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='word',
        ),
        migrations.AddField(
            model_name='courses',
            name='word',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Words'),
        ),
    ]
