# Generated by Django 3.0.2 on 2020-01-12 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_auto_20200112_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses',
            name='word',
            field=models.ManyToManyField(blank=True, to='courses.Words'),
        ),
    ]
