# Generated by Django 3.0.2 on 2020-01-12 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200112_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='users',
            new_name='user',
        ),
    ]
