# Generated by Django 3.0.2 on 2020-01-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200112_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
