# Generated by Django 3.0.2 on 2020-01-19 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_auto_20200112_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_cur', to=settings.AUTH_USER_MODEL),
        ),
    ]
